import { createContext } from "react";

export const SupportedLanguages = [
  { language: "Afrikaans", locale: "af" },
  { language: "Albanian", locale: "sq" },
  { language: "Amharic", locale: "am" },
  { language: "Arabic", locale: "ar" },
  { language: "Armenian", locale: "hy" },
  { language: "Assamese", locale: "as" },
  { language: "Aymara", locale: "ay" },
  { language: "Azerbaijani", locale: "az" },
  { language: "Bambara", locale: "bm" },
  { language: "Basque", locale: "eu" },
  { language: "Belarusian", locale: "be" },
  { language: "Bengali", locale: "bn" },
  { language: "Bhojpuri", locale: "bho" },
  { language: "Bosnian", locale: "bs" },
  { language: "Bulgarian", locale: "bg" },
  { language: "Catalan", locale: "ca" },
  { language: "Cebuano", locale: "ceb" },
  { language: "Chinese (Simplified)", locale: "zh-CN" },
  { language: "Chinese (Traditional)", locale: "zh-TW" },
  { language: "Corsican", locale: "co" },
  { language: "Croatian", locale: "hr" },
  { language: "Czech", locale: "cs" },
  { language: "Danish", locale: "da" },
  { language: "Dhivehi", locale: "dv" },
  { language: "Dogri", locale: "doi" },
  { language: "Dutch", locale: "nl" },
  { language: "English", locale: "en" },
  { language: "Esperanto", locale: "eo" },
  { language: "Estonian", locale: "et" },
  { language: "Ewe", locale: "ee" },
  { language: "Filipino (Tagalog)", locale: "fil" },
  { language: "Finnish", locale: "fi" },
  { language: "French", locale: "fr" },
  { language: "Frisian", locale: "fy" },
  { language: "Galician", locale: "gl" },
  { language: "Georgian", locale: "ka" },
  { language: "German", locale: "de" },
  { language: "Greek", locale: "el" },
  { language: "Guarani", locale: "gn" },
  { language: "Gujarati", locale: "gu" },
  { language: "Haitian Creole", locale: "ht" },
  { language: "Hausa", locale: "ha" },
  { language: "Hawaiian", locale: "haw" },
  { language: "Hebrew", locale: "he or iw" },
  { language: "Hindi", locale: "hi" },
  { language: "Hmong", locale: "hmn" },
  { language: "Hungarian", locale: "hu" },
  { language: "Icelandic", locale: "is" },
  { language: "Igbo", locale: "ig" },
  { language: "Ilocano", locale: "ilo" },
  { language: "Indonesian", locale: "id" },
  { language: "Irish", locale: "ga" },
  { language: "Italian", locale: "it" },
  { language: "Japanese", locale: "ja" },
  { language: "Javanese", locale: "jv or jw" },
  { language: "Kannada", locale: "kn" },
  { language: "Kazakh", locale: "kk" },
  { language: "Khmer", locale: "km" },
  { language: "Kinyarwanda", locale: "rw" },
  { language: "Konkani", locale: "gom" },
  { language: "Korean", locale: "ko" },
  { language: "Krio", locale: "kri" },
  { language: "Kurdish", locale: "ku" },
  { language: "Kurdish (Sorani)", locale: "ckb" },
  { language: "Kyrgyz", locale: "ky" },
  { language: "Lao", locale: "lo" },
  { language: "Latin", locale: "la" },
  { language: "Latvian", locale: "lv" },
  { language: "Lingala", locale: "ln" },
  { language: "Lithuanian", locale: "lt" },
  { language: "Luganda", locale: "lg" },
  { language: "Luxembourgish", locale: "lb" },
  { language: "Macedonian", locale: "mk" },
  { language: "Maithili", locale: "mai" },
  { language: "Malagasy", locale: "mg" },
  { language: "Malay", locale: "ms" },
  { language: "Malayalam", locale: "ml" },
  { language: "Maltese", locale: "mt" },
  { language: "Maori", locale: "mi" },
  { language: "Marathi", locale: "mr" },
  { language: "Meiteilon (Manipuri)", locale: "mni-Mtei" },
  { language: "Mizo", locale: "lus" },
  { language: "Mongolian", locale: "mn" },
  { language: "Myanmar (Burmese)", locale: "my" },
  { language: "Nepali", locale: "ne" },
  { language: "Norwegian", locale: "no" },
  { language: "Nyanja (Chichewa)", locale: "ny" },
  { language: "Odia (Oriya)", locale: "or" },
  { language: "Oromo", locale: "om" },
  { language: "Pashto", locale: "ps" },
  { language: "Persian", locale: "fa" },
  { language: "Polish", locale: "pl" },
  { language: "Portuguese (Portugal, Brazil)", locale: "pt" },
  { language: "Punjabi", locale: "pa" },
  { language: "Quechua", locale: "qu" },
  { language: "Romanian", locale: "ro" },
  { language: "Russian", locale: "ru" },
  { language: "Samoan", locale: "sm" },
  { language: "Sanskrit", locale: "sa" },
  { language: "Scots Gaelic", locale: "gd" },
  { language: "Sepedi", locale: "nso" },
  { language: "Serbian", locale: "sr" },
  { language: "Sesotho", locale: "st" },
  { language: "Shona", locale: "sn" },
  { language: "Sindhi", locale: "sd" },
  { language: "Sinhala (Sinhalese)", locale: "si" },
  { language: "Slovak", locale: "sk" },
  { language: "Slovenian", locale: "sl" },
  { language: "Somali", locale: "so" },
  { language: "Spanish", locale: "es" },
  { language: "Sundanese", locale: "su" },
  { language: "Swahili", locale: "sw" },
  { language: "Swedish", locale: "sv" },
  { language: "Tagalog (Filipino)", locale: "tl" },
  { language: "Tajik", locale: "tg" },
  { language: "Tamil", locale: "ta" },
  { language: "Tatar", locale: "tt" },
  { language: "Telugu", locale: "te" },
  { language: "Thai", locale: "th" },
  { language: "Tigrinya", locale: "ti" },
  { language: "Tsonga", locale: "ts" },
  { language: "Turkish", locale: "tr" },
  { language: "Turkmen", locale: "tk" },
  { language: "Twi (Akan)", locale: "ak" },
  { language: "Ukrainian", locale: "uk" },
  { language: "Urdu", locale: "ur" },
  { language: "Uyghur", locale: "ug" },
  { language: "Uzbek", locale: "uz" },
  { language: "Vietnamese", locale: "vi" },
  { language: "Welsh", locale: "cy" },
  { language: "Xhosa", locale: "xh" },
  { language: "Yiddish", locale: "yi" },
  { language: "Yoruba", locale: "yo" },
  { language: "Zulu", locale: "zu}" },
];

export const LocaleContext = createContext<string>("en");
